# Generated by Django 2.0.7 on 2018-07-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecategory',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
