# Generated by Django 2.0.7 on 2018-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='meta_description',
            field=models.CharField(max_length=560),
        ),
    ]
