# Generated by Django 2.0.7 on 2018-07-10 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20180709_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default='2018-07-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default='2018-07-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websitecategory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
