# Generated by Django 2.0.7 on 2018-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20180712_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='meta_description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
