# Generated by Django 2.0.7 on 2018-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20180710_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
