# Generated by Django 2.0.7 on 2018-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_auto_20180710_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=12)),
            ],
        ),
    ]
