# Generated by Django 2.0.7 on 2018-07-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='website',
            field=models.CharField(max_length=128),
        ),
    ]
